/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyBusinessRouteImport } from './routes/verify-business'
import { Route as UploadReceiptRouteImport } from './routes/upload-receipt'
import { Route as TransparencyRouteImport } from './routes/transparency'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as EyespyrRouteImport } from './routes/eyespyr'
import { Route as IndexRouteImport } from './routes/index'

const VerifyBusinessRoute = VerifyBusinessRouteImport.update({
  id: '/verify-business',
  path: '/verify-business',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadReceiptRoute = UploadReceiptRouteImport.update({
  id: '/upload-receipt',
  path: '/upload-receipt',
  getParentRoute: () => rootRouteImport,
} as any)
const TransparencyRoute = TransparencyRouteImport.update({
  id: '/transparency',
  path: '/transparency',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const EyespyrRoute = EyespyrRouteImport.update({
  id: '/eyespyr',
  path: '/eyespyr',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/eyespyr': typeof EyespyrRoute
  '/how-it-works': typeof HowItWorksRoute
  '/network': typeof NetworkRoute
  '/pricing': typeof PricingRoute
  '/scan': typeof ScanRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/transparency': typeof TransparencyRoute
  '/upload-receipt': typeof UploadReceiptRoute
  '/verify-business': typeof VerifyBusinessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/eyespyr': typeof EyespyrRoute
  '/how-it-works': typeof HowItWorksRoute
  '/network': typeof NetworkRoute
  '/pricing': typeof PricingRoute
  '/scan': typeof ScanRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/transparency': typeof TransparencyRoute
  '/upload-receipt': typeof UploadReceiptRoute
  '/verify-business': typeof VerifyBusinessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/eyespyr': typeof EyespyrRoute
  '/how-it-works': typeof HowItWorksRoute
  '/network': typeof NetworkRoute
  '/pricing': typeof PricingRoute
  '/scan': typeof ScanRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/transparency': typeof TransparencyRoute
  '/upload-receipt': typeof UploadReceiptRoute
  '/verify-business': typeof VerifyBusinessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/eyespyr'
    | '/how-it-works'
    | '/network'
    | '/pricing'
    | '/scan'
    | '/sitemap.xml'
    | '/transparency'
    | '/upload-receipt'
    | '/verify-business'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/eyespyr'
    | '/how-it-works'
    | '/network'
    | '/pricing'
    | '/scan'
    | '/sitemap.xml'
    | '/transparency'
    | '/upload-receipt'
    | '/verify-business'
  id:
    | '__root__'
    | '/'
    | '/eyespyr'
    | '/how-it-works'
    | '/network'
    | '/pricing'
    | '/scan'
    | '/sitemap.xml'
    | '/transparency'
    | '/upload-receipt'
    | '/verify-business'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EyespyrRoute: typeof EyespyrRoute
  HowItWorksRoute: typeof HowItWorksRoute
  NetworkRoute: typeof NetworkRoute
  PricingRoute: typeof PricingRoute
  ScanRoute: typeof ScanRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TransparencyRoute: typeof TransparencyRoute
  UploadReceiptRoute: typeof UploadReceiptRoute
  VerifyBusinessRoute: typeof VerifyBusinessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-business': {
      id: '/verify-business'
      path: '/verify-business'
      fullPath: '/verify-business'
      preLoaderRoute: typeof VerifyBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload-receipt': {
      id: '/upload-receipt'
      path: '/upload-receipt'
      fullPath: '/upload-receipt'
      preLoaderRoute: typeof UploadReceiptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transparency': {
      id: '/transparency'
      path: '/transparency'
      fullPath: '/transparency'
      preLoaderRoute: typeof TransparencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eyespyr': {
      id: '/eyespyr'
      path: '/eyespyr'
      fullPath: '/eyespyr'
      preLoaderRoute: typeof EyespyrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EyespyrRoute: EyespyrRoute,
  HowItWorksRoute: HowItWorksRoute,
  NetworkRoute: NetworkRoute,
  PricingRoute: PricingRoute,
  ScanRoute: ScanRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TransparencyRoute: TransparencyRoute,
  UploadReceiptRoute: UploadReceiptRoute,
  VerifyBusinessRoute: VerifyBusinessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
